version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      - backend/.dev.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python manage.py runserver
    volumes:
      - "/home/marek/PycharmProjects/cargo/app:/app:ro"
    env_file:
      - backend/.dev.env
    ports:
      - "8080:8000"
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    expose:
      - 6379

volumes:
  pgdata: {}